CREATE DATABASE DISTRIBUIDORA
GO
USE DISTRIBUIDORA
GO
CREATE TABLE CLIENTES(
Id INT PRIMARY KEY IDENTITY,
Nombre VARCHAR(50),
DESCUENTO DECIMAL(18,2)
)
CREATE TABLE PRODUCTOS(
IdProducto INT PRIMARY KEY IDENTITY,
NombreProducto VARCHAR(50),
Costo decimal(18,2),
Unidades int,
IdCliente int foreign key references CLIENTES(Id)
)
INSERT INTO CLIENTES VALUES('Juan',100)
INSERT INTO CLIENTES VALUES('Pedro',200)
INSERT INTO CLIENTES VALUES('Jose',500)
INSERT INTO CLIENTES VALUES('Ana',240)

INSERT INTO PRODUCTOS VALUES('Pc',450,2,1)
INSERT INTO PRODUCTOS VALUES('Laptop',250,3,3)
INSERT INTO PRODUCTOS VALUES('Celular',280,3,4)
INSERT INTO PRODUCTOS VALUES('Mouse',90,4,1)